sudo: false

# Blacklist
branches:
  except:
    - gh-pages

# Environment variables
env:
  global:
    - MAKEFLAGS="-j 2"
    - CC=gcc-7
    - CXX=g++-7
    - GH_REPO_NAME: nissa
    - GH_REPO_REF: github.com/sunpho84/nissa.git

# Install dependencies
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-6.0 main'
        key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
    packages:
      - g++-7
      - gfortran
      - libopenmpi-dev
      - libblas-dev
      - libeigen3-dev

script:
  - bash config/install_parpack.sh
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PWD/arpack-ng/install/lib
  - bash config/bootstrap
  - mkdir build
  - cd build
  - ../configure
  - make
